export const levels=['yearly','monthly','weekly','daily'] as const;
export type Level=typeof levels[number];
export type Priority='low'|'medium'|'high'|'urgent';
export type Status='planned'|'active'|'blocked'|'done';
export type Recurrence='none'|'daily'|'weekly'|'monthly'|'yearly';
export type Task={id:string;user_id?:string;parent_id:string|null;title:string;notes:string;level:Level;start_date:string|null;due:string;start_time:string|null;end_time:string|null;priority:Priority;status:Status;done:boolean;recurrence:Recurrence;estimate_minutes:number;tags:string[];sort_order:number;created_at?:string;updated_at?:string};
export type Attachment={id:string;task_id:string;user_id?:string;name:string;storage_path:string;mime_type:string;file_size:number;created_at?:string};
export type TaskLink={id:string;source_id:string;target_id:string;user_id?:string};
export type View='overview'|'yearly'|'monthly'|'weekly'|'daily'|'board'|'calendar'|'focus';
export const dateKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
export const parseDate=(value:string)=>new Date(`${value}T12:00:00`);
export function addDays(date:Date,n:number){const d=new Date(date);d.setDate(d.getDate()+n);return d}
export function startOfWeek(date:Date){return addDays(date,-((date.getDay()+6)%7))}
export function monthLast(date:Date){return new Date(date.getFullYear(),date.getMonth()+1,0)}
export function period(level:Level,date:Date):[string,string]{const start=level==='yearly'?new Date(date.getFullYear(),0,1):level==='monthly'?new Date(date.getFullYear(),date.getMonth(),1):level==='weekly'?startOfWeek(date):date;const end=level==='yearly'?new Date(date.getFullYear(),11,31):level==='monthly'?monthLast(date):level==='weekly'?addDays(start,6):start;return [dateKey(start),dateKey(end)]}
export function matchesPeriod(task:Task,level:Level,date:Date){const [a,b]=period(level,date);const start=task.start_date||task.due;return start<=b&&task.due>=a}
export function ancestors(task:Task,tasks:Task[]){const result:Task[]=[];const seen=new Set([task.id]);let cur=task;while(cur.parent_id){const next=tasks.find(t=>t.id===cur.parent_id);if(!next||seen.has(next.id))break;result.unshift(next);seen.add(next.id);cur=next}return result}
export function descendants(id:string,tasks:Task[]){const result=new Set<string>();const queue=[id];while(queue.length){const cur=queue.shift()!;if(result.has(cur))continue;result.add(cur);for(const task of tasks)if(task.parent_id===cur&&!result.has(task.id))queue.push(task.id)}return result}
export function progress(id:string,tasks:Task[]){const children=tasks.filter(t=>t.parent_id===id);if(!children.length)return tasks.find(t=>t.id===id)?.done?100:0;return Math.round(children.reduce((sum,t)=>sum+progress(t.id,tasks),0)/children.length)}
export function dateTitle(view:Level,date:Date){if(view==='yearly')return String(date.getFullYear());if(view==='monthly')return date.toLocaleDateString('en-AU',{month:'long',year:'numeric'});if(view==='weekly'){const start=startOfWeek(date);return `${start.toLocaleDateString('en-AU',{day:'numeric',month:'short'})} — ${addDays(start,6).toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'})}`}return date.toLocaleDateString('en-AU',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
export function movePeriod(level:Level,date:Date,n:number){const d=new Date(date);if(level==='yearly')d.setFullYear(d.getFullYear()+n);if(level==='monthly')d.setMonth(d.getMonth()+n);if(level==='weekly')d.setDate(d.getDate()+7*n);if(level==='daily')d.setDate(d.getDate()+n);return d}
export function blankTask(level:Level,date:Date,parent_id:string|null=null):Task{const [start,due]=period(level,date);return {id:crypto.randomUUID(),parent_id,title:'',notes:'',level,start_date:start,due,start_time:null,end_time:null,priority:'medium',status:'planned',done:false,recurrence:'none',estimate_minutes:30,tags:[],sort_order:0}}
export function getSuggestedSteps(parent:Task,level:Level):Task[]{const count=level==='monthly'?3:level==='weekly'?4:level==='daily'?5:2;const titles=level==='monthly'?['Define the milestone','Complete the main deliverable','Review results and adjust']:level==='weekly'?['Set this week’s outcome','Start the highest-impact action','Complete the essential work','Review progress and prepare next steps']:level==='daily'?['Clarify the next action','Gather everything needed','Work on the highest-priority step','Check and refine the result','Record progress']:['Define the objective','Turn it into a measurable plan'];const start=parseDate(parent.start_date||parent.due);const end=parseDate(parent.due);return Array.from({length:count},(_,i)=>{const day=addDays(start,Math.max(0,Math.floor(((end.getTime()-start.getTime())/86400000)*(i+1)/count)));const task=blankTask(level,day,parent.id);return {...task,title:`${titles[i]} — ${parent.title}`,due:dateKey(day),start_date:dateKey(day),notes:`Suggested step for: ${parent.title}`}})}
